### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [webqit/oohtml#3]
Hi everyone.

I want to help, but I want to know if this project is active. *Is this project active?*

**Comment by ox-harris** [comment]
Hi Code Hangen,

Yes this project is active and it'll be cool to have you help with anything.

**Comment by ox-harris** [comment]
OK. What would be the use case?

**Comment by ox-harris** [comment]
I get that really well. Very useful. And that would be in the case of Modules with remote content, using the `src` attribute:

```html
<head>
    <template name="module1" src="/content.html" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"> </template>
</head>
```

PSS: the `name` attribute is for API access:

```js
const { module1 } = document.templates;
```

**Comment by ox-harris** [comment]
Just seeing ur edits featuring options 1, 2, 3, 4. Didn't follow well with 1, 2, and 3.

**Comment by ox-harris** [comment]
Sure @codehangen, I do welcome the SRI idea for HTML Modules with remote content (`<template src="..." integrity="..."></template>`).

I should slate that for a near-future release.

**Comment by ox-harris** [comment]
BTW: OOHTML is getting a major rewrite soon. Embodies the same decalstive way of working; just better!

**Comment by ox-harris** [comment]
You already automatically show on the contributors list, if you take a look. 😃

**Comment by ox-harris** [comment]
Hi @codehangen , I'm glad about that. Thanks for your input.
