### ISSUE TITLE
cdn for oohtml?

### ISSUE THREAD

**Issue by ghost** [webqit/oohtml#4]
Hi everyone.

Have you thought about having a cdn network (content delivery network) to host the libraries, templates for the oohtml community?

#### an idea
```html
<script src="https://cdn.demo.com/npm/oohtml@2.3.0-alpha1/dist/js/oohtml.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
```

#### why?
1. CDNs help reduce the bandwidth demands on origin servers, reducing bandwidth and web hosting costs for website owners. In general, going with a CDN provider will help businesses do away with the costs of setting up infrastructure, hosting and servers across the globe.
2. CDNs are used widely for delivering stylesheets and JavaScript files (static assets) of libraries like Bootstrap, jQuery etc.
3. Serving libraries' static assets over CDN lowers the request burden on an organization's own servers.

#### question/feedback
*what do you all think of the idea?*

**Comment by ox-harris** [comment]
Hi Code Hangen,

Thanks for your question. We definitely have. Our libraries are available
as npm packages and therefore automatically available via the unpkg cdn.

For example, oohtml is here:

***@***.***/oohtml/dist/main.js

Docs were down temporarily, but you can find these info in the docs.

Let me know if I answered your question.

Thanks.
